import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Screen } from '@qupid/core';
import { useCoaches } from '../../../shared/hooks/useCoaches';
import { AI_COACHES } from '@qupid/core';
const CoachCard = ({ coach, onStart }) => (_jsxs("div", { className: "p-4 bg-white rounded-xl border border-[#F2F4F6] flex items-center space-x-4 transition-all hover:shadow-lg hover:border-[#DB7093] hover:-translate-y-0.5 cursor-pointer group", onClick: onStart, children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("img", { src: coach.avatar, alt: coach.name, className: "w-16 h-16 rounded-full object-cover border-2 border-white shadow-sm group-hover:border-[#DB7093] transition-colors" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("p", { className: "font-bold text-base text-[#191F28] mb-1", children: [coach.name, " \uCF54\uCE58"] }), _jsxs("p", { className: "text-sm font-semibold text-[#4F7ABA] mb-1", children: [coach.specialty, " \uC804\uBB38"] }), _jsx("p", { className: "text-xs text-[#8B95A1] leading-relaxed", children: coach.tagline })] }), _jsx("div", { className: "flex-shrink-0", children: _jsx("button", { className: "px-4 py-2 bg-[#FDF2F8] text-sm text-[#DB7093] font-bold rounded-full transition-all hover:bg-[#DB7093] hover:text-white hover:shadow-md whitespace-nowrap", onClick: (e) => {
                    e.stopPropagation();
                    onStart();
                }, children: "\uC0C1\uB2F4 \uC2DC\uC791" }) })] }));
const CoachingTabScreen = ({ onNavigate, onStartCoachChat }) => {
    const { data: apiCoaches = [], isLoading } = useCoaches();
    const coaches = apiCoaches.length > 0 ? apiCoaches : AI_COACHES;
    return (_jsxs("div", { className: "flex flex-col h-full w-full bg-[#F9FAFB]", children: [_jsx("header", { className: "flex-shrink-0 p-4 pt-5 bg-white border-b border-[#F2F4F6]", children: _jsx("h1", { className: "text-2xl font-bold text-[#191F28]", children: "\uCF54\uCE6D" }) }), _jsxs("main", { className: "flex-1 overflow-y-auto p-4 space-y-6 pb-24", children: [_jsxs("section", { children: [_jsxs("div", { className: "mb-4", children: [_jsx("h2", { className: "text-lg font-bold text-[#191F28] mb-2", children: "1:1 \uB9DE\uCDA4 \uCF54\uCE6D \uD83C\uDF93" }), _jsx("p", { className: "text-sm text-[#8B95A1] leading-relaxed", children: "\uBD80\uC871\uD55C \uBD80\uBD84\uC744 \uC804\uBB38 \uCF54\uCE58\uC640 \uD568\uAED8 \uC9D1\uC911\uC801\uC73C\uB85C \uC5F0\uC2B5\uD574\uBCF4\uC138\uC694." })] }), _jsx("div", { className: "space-y-3", children: isLoading ? (_jsx("div", { className: "flex justify-center items-center py-8", children: _jsx("div", { className: "animate-spin rounded-full h-12 w-12 border-b-2 border-[#0AC5A8]" }) })) : (coaches.map(coach => (_jsx(CoachCard, { coach: coach, onStart: () => {
                                        if (onStartCoachChat) {
                                            onStartCoachChat(coach);
                                        }
                                        else {
                                            // Fallback to navigate to Chat screen
                                            onNavigate(Screen.Chat);
                                        }
                                    } }, coach.id)))) })] }), _jsxs("section", { children: [_jsx("h2", { className: "font-bold text-lg px-1 mb-3", children: "\uB9DE\uCDA4 \uD559\uC2B5 \uCF58\uD150\uCE20 \uD83D\uDCA1" }), _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "p-4 bg-white rounded-xl border border-[#F2F4F6] cursor-pointer transition-all hover:shadow-lg hover:border-blue-400 hover:-translate-y-0.5 group", children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-semibold text-blue-600 text-sm mb-2", children: "\uCD94\uCC9C \uAC15\uC758" }), _jsx("p", { className: "font-bold text-base text-[#191F28] leading-tight mb-2", children: "\uACF5\uAC10 \uB2A5\uB825 \uD5A5\uC0C1\uC2DC\uD0A4\uAE30: \uC0C1\uB300\uC758 \uB9C8\uC74C\uC744 \uC5BB\uB294 3\uAC00\uC9C0 \uC9C8\uBB38\uBC95" }), _jsx("p", { className: "text-sm text-[#8B95A1]", children: "15\uBD84 \uAC15\uC758 \u00B7 75% \uC218\uAC15" })] }), _jsx("div", { className: "ml-3 flex-shrink-0", children: _jsx("div", { className: "w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center group-hover:bg-blue-100 transition-colors", children: _jsx("span", { className: "text-blue-600 text-lg", children: "\uD83D\uDCDA" }) }) })] }) }), _jsx("div", { className: "p-4 bg-white rounded-xl border border-[#F2F4F6] cursor-pointer transition-all hover:shadow-lg hover:border-green-400 hover:-translate-y-0.5 group", children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-semibold text-green-600 text-sm mb-2", children: "\uC2E4\uC804 \uD301" }), _jsx("p", { className: "font-bold text-base text-[#191F28] leading-tight mb-2", children: "\uC5B4\uC0C9\uD55C \uCE68\uBB35 \uAE68\uAE30: 5\uAC00\uC9C0 \uC720\uC6A9\uD55C \uB300\uD654 \uC8FC\uC81C" }), _jsx("p", { className: "text-sm text-[#8B95A1]", children: "3\uBD84 \uBD84\uB7C9" })] }), _jsx("div", { className: "ml-3 flex-shrink-0", children: _jsx("div", { className: "w-12 h-12 bg-green-50 rounded-full flex items-center justify-center group-hover:bg-green-100 transition-colors", children: _jsx("span", { className: "text-green-600 text-lg", children: "\uD83D\uDCA1" }) }) })] }) })] })] })] })] }));
};
export { CoachingTabScreen };
export default CoachingTabScreen;
