import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { SearchIcon, SettingsIcon, ArrowLeftIcon } from '@qupid/ui';
const PersonaCard = ({ persona, onSelect }) => {
    return (_jsxs("div", { className: "w-full p-5 flex flex-col bg-white rounded-2xl border border-[#F2F4F6] shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-all hover:shadow-lg hover:border-[#F093B0] cursor-pointer", onClick: onSelect, children: [_jsxs("div", { className: "flex items-start flex-grow", children: [_jsx("img", { src: persona.avatar, alt: persona.name, className: "w-20 h-20 rounded-xl object-cover" }), _jsxs("div", { className: "ml-4 flex-1", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("p", { className: "font-bold text-lg text-[#191F28]", children: [persona.name, ", ", persona.age] }), _jsx("div", { className: "flex items-center space-x-2", children: _jsxs("p", { className: "font-bold text-sm text-[#0AC5A8]", children: [persona.match_rate, "% \uB9DE\uC74C"] }) })] }), _jsxs("p", { className: "text-sm text-[#8B95A1] mt-0.5", children: [persona.job, " \u00B7 ", persona.mbti] }), _jsxs("p", { className: "text-base text-[#191F28] mt-2 font-medium", children: ["\"", persona.intro, "\""] })] })] }), _jsx("button", { className: "w-full h-10 bg-[#FDF2F8] text-[#F093B0] font-bold rounded-lg transition-colors hover:bg-opacity-80 mt-4", children: "\uB300\uD654\uD558\uAE30" })] }));
};
const PersonaSelection = ({ personas, userProfile, onSelect, onBack }) => {
    const [searchTerm, setSearchTerm] = useState('');
    const partnerGender = userProfile?.user_gender === 'female' ? 'male' : 'female';
    const filteredPersonas = personas
        .filter(p => p.gender === partnerGender)
        .filter(p => p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        p.tags.some((tag) => tag.toLowerCase().includes(searchTerm.toLowerCase())));
    return (_jsxs("div", { className: "flex flex-col h-full w-full bg-[#F9FAFB]", children: [_jsxs("header", { className: "flex-shrink-0 p-3 pt-4 bg-white border-b border-[#F2F4F6]", children: [_jsxs("div", { className: "flex justify-between items-center px-2", children: [_jsx("button", { onClick: onBack, className: "p-2 -ml-2 rounded-full hover:bg-gray-100", children: _jsx(ArrowLeftIcon, { className: "w-6 h-6 text-[#191F28]" }) }), _jsx("h1", { className: "text-xl font-bold text-[#191F28]", children: "\uCD94\uCC9C AI \uCE5C\uAD6C\uB4E4" }), _jsxs("button", { className: "flex items-center space-x-1 text-[#4F7ABA] font-medium p-2", children: [_jsx(SettingsIcon, { className: "w-5 h-5" }), _jsx("span", { className: "hidden sm:inline", children: "\uD544\uD130" })] })] }), _jsxs("div", { className: "mt-3 relative px-2", children: [_jsx(SearchIcon, { className: "absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-[#8B95A1]" }), _jsx("input", { type: "text", placeholder: "\uC774\uB984\uC774\uB098 \uD2B9\uC131\uC73C\uB85C \uAC80\uC0C9", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full h-11 pl-11 pr-4 bg-[#F2F4F6] rounded-full focus:outline-none focus:ring-2 focus:ring-[#F093B0]" })] })] }), _jsxs("main", { className: "flex-1 overflow-y-auto p-5", children: [_jsx("div", { className: "space-y-4", children: filteredPersonas.map((persona, i) => (_jsx("div", { className: "animate-fade-in-up", style: { animationDelay: `${i * 100}ms` }, children: _jsx(PersonaCard, { persona: persona, onSelect: () => onSelect(persona) }) }, persona.id))) }), _jsxs("div", { className: "mt-8 p-5 bg-[#F7F4FF] rounded-xl text-center", children: [_jsx("p", { className: "font-bold text-base text-[#191F28]", children: "\uD83D\uDCA1 \uB354 \uB9CE\uC740 AI \uCE5C\uAD6C\uB4E4" }), _jsx("p", { className: "text-sm text-[#6C7680] mt-1", children: "\uB9E4\uC77C \uC0C8\uB85C\uC6B4 \uD398\uB974\uC18C\uB098\uAC00 \uCD94\uAC00\uB3FC\uC694. \uB0B4\uC77C \uB610 \uB2E4\uB978 \uCE5C\uAD6C\uB97C \uB9CC\uB098\uBCF4\uC138\uC694!" })] })] })] }));
};
export { PersonaSelection };
export default PersonaSelection;
