import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeftIcon, CoachKeyIcon } from '@qupid/ui';
import { TUTORIAL_STEPS } from '@qupid/core';
const TutorialIntroScreen = ({ persona, onStart, onBack, onComplete }) => {
    const tutorialGoals = TUTORIAL_STEPS.slice(0, 4).map(step => step.title.split(': ')[1]);
    return (_jsxs("div", { className: "flex flex-col h-full w-full bg-white animate-fade-in", children: [_jsx("header", { className: "flex-shrink-0 flex items-center p-3", children: _jsx("button", { onClick: onBack, className: "p-2 rounded-full hover:bg-gray-100", children: _jsx(ArrowLeftIcon, { className: "w-6 h-6 text-[#8B95A1]" }) }) }), _jsxs("main", { className: "flex-1 px-6 text-center", children: [_jsx("img", { src: persona?.avatar || '/default-avatar.png', alt: persona?.name || 'AI 친구', className: "w-24 h-24 rounded-full mx-auto shadow-lg" }), _jsx("h1", { className: "mt-4 text-2xl font-bold text-[#191F28]", children: "\uCCAB \uB300\uD654 \uD29C\uD1A0\uB9AC\uC5BC" }), _jsxs("p", { className: "text-base text-[#8B95A1] mt-2", children: ["\uCCAB \uB300\uD654\uB294 AI \uCE5C\uAD6C ", _jsx("span", { className: "font-bold text-[#F093B0]", children: persona?.name || 'AI 친구' }), "\uB2D8\uACFC \uD568\uAED8\uD574\uC694."] }), _jsxs("div", { className: "mt-8 p-6 bg-[#F9FAFB] border border-[#E5E8EB] rounded-2xl text-left", children: [_jsx("h2", { className: "text-lg font-bold text-[#191F28]", children: "\uD29C\uD1A0\uB9AC\uC5BC \uBAA9\uD45C \uD83C\uDFAF" }), _jsx("p", { className: "mt-1 text-sm text-gray-600", children: "\uC774 \uD29C\uD1A0\uB9AC\uC5BC\uC744 \uD1B5\uD574 \uB300\uD654\uC758 \uAE30\uBCF8\uAE30\uB97C \uB2E4\uC838\uBD10\uC694." }), _jsx("ul", { className: "mt-4 space-y-3", children: tutorialGoals.map((goal, i) => (_jsxs("li", { className: "flex items-center", children: [_jsx("span", { className: "text-lg mr-3 text-[#0AC5A8]", children: "\u2713" }), _jsx("p", { className: "text-base text-[#191F28] font-medium", children: goal })] }, i))) })] }), _jsxs("div", { className: "mt-4 p-5 bg-[#EBF2FF] rounded-2xl text-left", children: [_jsxs("h2", { className: "text-lg font-bold text-[#191F28] flex items-center", children: [_jsx(CoachKeyIcon, { className: "w-5 h-5 mr-2 text-yellow-500" }), "\uC2E4\uC2DC\uAC04 \uCF54\uCE6D"] }), _jsx("p", { className: "mt-2 text-sm text-[#4F7ABA] leading-relaxed font-medium", children: "\uB300\uD654 \uC911\uC5D0 AI \uCF54\uCE58\uAC00 \uC2E4\uC2DC\uAC04\uC73C\uB85C \uD301\uC744 \uB4DC\uB9B4 \uAC70\uC608\uC694. \uB9C9\uD788\uB294 \uBD80\uBD84\uC774 \uC788\uC5B4\uB3C4 \uAC71\uC815\uD558\uC9C0 \uB9C8\uC138\uC694!" })] })] }), _jsx("footer", { className: "flex-shrink-0 p-4", children: _jsx("button", { onClick: onStart || onComplete, className: "w-full h-14 bg-[#F093B0] text-white text-lg font-bold rounded-xl", children: "\uD29C\uD1A0\uB9AC\uC5BC \uC2DC\uC791\uD558\uAE30" }) })] }));
};
export { TutorialIntroScreen };
export default TutorialIntroScreen;
