import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeftIcon } from '@qupid/ui';
const FavoritesScreen = ({ personas, onSelectPersona, onBack }) => {
    return (_jsxs("div", { className: "flex flex-col h-full w-full bg-white", children: [_jsxs("header", { className: "flex-shrink-0 flex items-center justify-between p-3 border-b border-[#F2F4F6]", children: [_jsx("div", { className: "w-14", children: _jsx("button", { onClick: onBack, className: "p-2 rounded-full hover:bg-gray-100", children: _jsx(ArrowLeftIcon, { className: "w-6 h-6 text-[#8B95A1]" }) }) }), _jsxs("div", { className: "text-center", children: [_jsx("h2", { className: "text-lg font-bold text-[#191F28]", children: "\uC990\uACA8\uCC3E\uB294 AI \uCE5C\uAD6C\uB4E4" }), _jsx("p", { className: "text-sm text-[#8B95A1]", children: "\uC790\uC8FC \uB300\uD654\uD558\uB294 AI\uB4E4\uC774\uC5D0\uC694" })] }), _jsx("button", { className: "p-2 w-14 rounded-full text-[#4F7ABA] font-semibold text-base", children: "\uD3B8\uC9D1" })] }), _jsx("main", { className: "flex-1 overflow-y-auto", children: personas.length > 0 ? (_jsx("ul", { className: "divide-y divide-[#F2F4F6]", children: personas.map(persona => (_jsxs("li", { onClick: () => onSelectPersona(persona), className: "p-4 flex items-center cursor-pointer hover:bg-gray-50", children: [_jsx("img", { src: persona.avatar, alt: persona.name, className: "w-14 h-14 rounded-full object-cover" }), _jsxs("div", { className: "flex-1 ml-4", children: [_jsx("p", { className: "font-bold text-base text-[#191F28]", children: persona.name }), _jsx("p", { className: "text-sm text-[#0AC5A8] font-semibold", children: "\uD83D\uDFE2 \uC628\uB77C\uC778" }), _jsx("p", { className: "text-xs text-[#8B95A1]", children: "\uC5B4\uC81C 25\uBD84 \uB300\uD654" })] }), _jsx("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    onSelectPersona(persona);
                                }, className: "px-4 py-2 bg-[#F093B0] text-white text-sm font-bold rounded-full", children: "\uB300\uD654\uD558\uAE30" })] }, persona.id))) })) : (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-center p-8", children: [_jsx("p", { className: "text-5xl mb-4", children: "\uD83D\uDC94" }), _jsx("p", { className: "text-xl font-bold text-[#191F28]", children: "\uC990\uACA8\uCC3E\uB294 \uCE5C\uAD6C\uAC00 \uC5C6\uC5B4\uC694" }), _jsxs("p", { className: "text-base text-[#8B95A1] mt-2", children: ["\uB9C8\uC74C\uC5D0 \uB4DC\uB294 AI\uC758 \uD504\uB85C\uD544\uC5D0\uC11C", _jsx("br", {}), "\uD558\uD2B8 \uBC84\uD2BC\uC744 \uB20C\uB7EC \uCD94\uAC00\uD574\uBCF4\uC138\uC694!"] })] })) })] }));
};
export { FavoritesScreen };
export default FavoritesScreen;
